---

- name: Install notmuch packages
  apt: pkg={{ item }}
       state=present
  with_items: notmuch_packages
  sudo: True

- name: copy notmuch config
  template: src=notmuch-config.j2
            dest=~/.notmuch-config
