---

- name: Main Configuration playbook for Gnus-much
# ========================================================
  hosts: 127.0.0.1
  connection: local

  vars_prompt:
    remote_host: "Please enter the HOST NAME of the remote mail server"
    remote_user: "Please enter your USER NAME on the remote mail server"
    remote_email: "Please enter your EMAIL on the remote mail server"
    remote_port: "Please enter the remote mail server's mail port"

  roles:
    - gnus
    - dovecot
    - offlineimap
    - notmuch